version: "3"

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  web:
    build: .
    image: ntub_python_assistant:latest
    ports:
      - "${WEB_PORT:-8500}:8500"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ASSISTANT_ID=${OPENAI_ASSISTANT_ID}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ASSISTANT_ROLE_NAME=${ASSISTANT_ROLE_NAME}
    <<: *logging
    restart: always
    volumes:
      - ./syssettings.json:/app/syssettings.json