version: "3"

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  web:
    build: .
    image: ntub_python_assistant:latest
    ports:
      - "8502:8502"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ASSISTANT_ID=${OPENAI_ASSISTANT_ID}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    <<: *logging
    restart: always
    volumes:
      - syssettings.json:/app/syssettings.json